### ISSUE TITLE
DEFINE-BITFIELD return value

### ISSUE THREAD

**Issue by phoe** [marcoheisig/bitfield#1]
https://github.com/marcoheisig/bitfield/blob/7ad1c77f81c8c2b8af0cae653a4504f326f897e2/code/bitfield.lisp#L214

To be consistent with many CL defining operators, I suggest returning `name` rather than the constructor name (which is the current behavior).

**Comment by marcoheisig** [comment]
Fixed.  Thanks for reporting!

By the way, does that mean you looked through my code and this was the only thing bothering you :D

**Comment by phoe** [comment]
<h1>Correct!</h1>

![Zrzut ekranu z 2020-10-22 14-29-20](https://user-images.githubusercontent.com/15045546/96871760-ff7ad780-1472-11eb-9901-6cf946650b68.png)

(Sorry, I felt like making a poor TF2 meta-meme would be somewhat appropriate here.)
